%8-th order bandpass filter
clf
Apass=5; %maximum ripple at passband
Astop=40; %minimum attenuation at stopband
Fs=500; % sampling frequency
Wr1=10/(Fs/2); 
Wp1=20/(Fs/2); 
Wp2=120/(Fs/2);
Wr2=140/(Fs/2);

[N, Wp] = ellipord([Wp1 Wp2], [Wr1 Wr2], Apass, Astop) %find order
[z,p,k]=ellip(N,Apass,Astop,Wp); %design digital Elliptic filter
[B, A]=zp2tf(z,p,k); %convert zp to transfer function
%B=[ 4.49938252e-002 -1.01952015e-001 7.64466628e-002 -9.01676003e-002 1.41510490e-001 -9.01676003e-002 7.64466628e-002 -1.01952015e-001 4.49938252e-002]
%A=[ 1.00000000e+000 -4.66446742e+000 1.07149840e+001 -1.62396019e+001 1.78271682e+001 -1.43691903e+001 8.29516289e+000 -3.14970301e+000 6.00870577e-001]

%Using Octave, study the quantization of filter coefficients
% the number b of bits is b = is + ds + 1
if 0
    is=7; % number of bits for integer part
    ds=8; % number of bits for decimal part
    Bq=fixed(is,ds,B);
    Aq=fixed(is,ds,A);
end
%The results generated by Octave is:
Aq=[  1.00000000e+000 -4.66796875e+000 1.07148438e+001 -1.62421875e+001 1.78242188e+001 -1.43710938e+001 8.29296875e+000 -3.15234375e+000 5.97656250e-001];
Bq=[  4.29687500e-002 -1.05468750e-001 7.42187500e-002 -9.37500000e-002 1.40625000e-001 -9.37500000e-002 7.42187500e-002 -1.05468750e-001 4.29687500e-002];

clf
zplane(B,A);
hold on
zerosBq = roots(Bq);
polesBq = roots(Aq);
plot(real(zerosBq),imag(zerosBq),'ro');
plot(real(polesBq),imag(polesBq),'rx','MarkerSize',11);
writeEPS('quantized_filter1_zp');

clf
[Hq,w]=freqz(Bq,Aq);
[H,w]=freqz(B,A);
plot(w,20*log10(abs(H)),'-x');
hold on
plot(w,20*log10(abs(Hq)),'--r');
grid
xlabel('\Omega (rad)');
ylabel('|H(e^{j \Omega})| (dB)');
legend('Original','Quantized');
axis tight
writeEPS('quantized_filter1');

%second case, more bits
clf
if 0
    is=10; % number of bits for integer part
    ds=15; % number of bits for decimal part
    Bq=fixed(is,ds,B);
    Aq=fixed(is,ds,A);
end
%The results generated by Octave is:
Aq=[  1.00000000e+000 -4.66448975e+000 1.07149658e+001 -1.62396240e+001 1.78271484e+001 -1.43692017e+001 8.29513550e+000 -3.14971924e+000 6.00860596e-001];
Bq=[  4.49829102e-002 -1.01959229e-001 7.64465332e-002 -9.01794434e-002 1.41510010e-001 -9.01794434e-002 7.64465332e-002 -1.01959229e-001 4.49829102e-002];

clf
[Hq,w]=freqz(Bq,Aq);
[H,w]=freqz(B,A);
plot(w,20*log10(abs(H)),'-x');
hold on
plot(w,20*log10(abs(Hq)),'--r');
grid
xlabel('\Omega (rad)');
ylabel('|H(e^{j \Omega})| (dB)');
legend('Original','Quantized');
axis tight
writeEPS('quantized_filter2');

%higher order filter
Astop=80; %minimum attenuation at stopband

[N, Wp] = ellipord([Wp1 Wp2], [Wr1 Wr2], Apass, Astop) %find order
[z,p,k]=ellip(N,Apass,Astop,Wp); %design digital Elliptic filter
[B, A]=zp2tf(z,p,k); %convert zp to transfer function
if 0
    is=10; % number of bits for integer part
    ds=15; % number of bits for decimal part
    Bq=fixed(is,ds,B);
    Aq=fixed(is,ds,A);
end
%The results generated by Octave is:
Bq=[  3.50952148e-003 -1.31225586e-002 1.76086426e-002 -1.65100098e-002 2.35595703e-002 -2.07824707e-002 2.56347656e-003 -3.05175781e-005 -2.59399414e-003 2.07519531e-002 -2.35900879e-002 1.64794922e-002 -1.76391602e-002 1.30920410e-002 -3.54003906e-003];
Aq=[  1.00000000e+000 -8.42071533e+000 3.52041016e+001 -9.73892517e+001 1.99647552e+002 -3.20799896e+002 4.16225616e+002 -4.42569916e+002 3.87353180e+002 -2.77711517e+002 1.60621155e+002 -7.27270508e+001 2.43822937e+001 -5.41464233e+000 5.99670410e-001];

clf
[Hq,w]=freqz(Bq,Aq);
[H,w]=freqz(B,A);
plot(w,20*log10(abs(H)),'-x');
hold on
plot(w,20*log10(abs(Hq)),'--r');
grid
xlabel('\Omega (rad)');
ylabel('|H(e^{j \Omega})| (dB)');
legend('Original','Quantized');
axis tight
writeEPS('quantized_filter3');

clf
zplane(B,A);
hold on
zerosBq = roots(Bq);
polesBq = roots(Aq);
plot(real(zerosBq),imag(zerosBq),'ro');
plot(real(polesBq),imag(polesBq),'rx','MarkerSize',11);
writeEPS('quantized_filter3_zp');
