%function createfigure
%CREATEFIGURE
clf
%  Auto-generated by MATLAB on 17-Mar-2009 00:27:41

% Create figure
figure1 = clf;

% Create line
annotation(figure1,'line',[0.3911 0.3911],[0.83 0.2548]);

d=0.2;
annotation(figure1,'line',[0.3911 0.3911]+d,[0.83 0.2548]);

% Create line
annotation(figure1,'line',[0.3661 0.415],[0.2585 0.2588]);
annotation(figure1,'line',[0.3661 0.415]+d,[0.2585 0.2588]);

% Create line
annotation(figure1,'line',[0.3692 0.4178],[0.6683 0.6683]);
annotation(figure1,'line',[0.3692 0.4178]+d,[0.6683 0.6683]);

% Create line
annotation(figure1,'line',[0.3691 0.4164],[0.4697 0.4698]);
annotation(figure1,'line',[0.3691 0.4164]+d,[0.4697 0.4698]);

% Create line
annotation(figure1,'line',[0.3691 0.4164],[0.8339 0.8342]);
annotation(figure1,'line',[0.3691 0.4164]+d,[0.8339 0.8342]);

annotation(figure1,'textbox','String',{' 0 (00)'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2839 0.2173 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{' 1 (01)'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2879 0.433 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{'2 (10)'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2914 0.6211 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{'3 (11)'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.295 0.7853 0.07143 0.0746]);

annotation(figure1,'textbox','String',{'-5'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2839+d 0.2173 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{'-2.5'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2879+d 0.433 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{'0'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2914+d 0.6211 0.07143 0.0746]);

% Create textbox
annotation(figure1,'textbox','String',{'2.5'},'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.295+d 0.7853 0.07143 0.0746]);


annotation(figure1,'textarrow',[0.3357 0.3875],[0.549 0.55],...
    'TextEdgeColor','none',...
    'String',{'D'});

annotation(figure1,'textarrow',[0.3357 0.3875]+d,[0.549 0.55],...
    'TextEdgeColor','none',...
    'String',{'A'});

writeEPS('conversion_ad');
