function [B,A]=dt_getChannelTransferFunction()
%
% Generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 24-Aug-2010 12:26:42
%

% Coefficient Format: Decimal

% Discrete-Time IIR Filter (real)
% -------------------------------
% Filter Structure    : Direct-Form II
% Numerator Length    : 13
% Denominator Length  : 13
% Stable              : Yes
% Linear Phase        : No

%Numerator:
B = [
    0.007120601713134337
    -0.0019222898834068854
    -0.025844549568524489
    0.0054572348136679933
    0.050806725273748889
    -0.0087782209645750498
    -0.063641939335278411
    0.0092490994846975896
    0.054301646307775862
    -0.0057386014785145989
    -0.029362003070503354
    0.0023980182814972214
    0.0093308294662545564
    ];

%Denominator:
A = [
    1
    -0.0000000000000049404924595819466
    2.7445577051566001
    -0.0000000000000087152507433074788
    4.4951584808973575
    -0.0000000000000040523140398818214
    4.6492043751470664
    -0.00000000000000055511151231257827
    3.2299784258838828
    0.000000000000001915134717478395
    1.4088842648092788
    0.0000000000000013183898417423734
    0.31451868286474216
    ];

%use column vectors to be compatible with zplane
B=transpose(B); 
A=transpose(A);

end